export interface Collectible {
    radius: number;
    backgroundColor: string;
    coordinates: CollectibleCoordinate[];
}

export interface CollectibleCoordinate {
    centerX: number;
    centerY: number;
}

export const collectibles: Collectible = {
    radius: 3,
    backgroundColor: '#ffb04b',
    coordinates: [
        convertToCoordinates(1, 1),
        convertToCoordinates(1, 2),
        convertToCoordinates(1, 3),
        convertToCoordinates(1, 4),
        convertToCoordinates(1, 5),
        convertToCoordinates(1, 6),
        convertToCoordinates(1, 7),
        convertToCoordinates(1, 8),
        convertToCoordinates(1, 9),
        convertToCoordinates(1, 10),
        convertToCoordinates(1, 11),
        convertToCoordinates(1, 12),
        convertToCoordinates(1, 15),
        convertToCoordinates(1, 16),
        convertToCoordinates(1, 17),
        convertToCoordinates(1, 18),
        convertToCoordinates(1, 19),
        convertToCoordinates(1, 20),
        convertToCoordinates(1, 21),
        convertToCoordinates(1, 22),
        convertToCoordinates(1, 23),
        convertToCoordinates(1, 24),
        convertToCoordinates(1, 25),
        convertToCoordinates(1, 26),

        convertToCoordinates(2, 1),
        convertToCoordinates(2, 6),
        convertToCoordinates(2, 12),
        convertToCoordinates(2, 15),
        convertToCoordinates(2, 21),
        convertToCoordinates(2, 26),

        convertToCoordinates(3, 1),
        convertToCoordinates(3, 6),
        convertToCoordinates(3, 12),
        convertToCoordinates(3, 15),
        convertToCoordinates(3, 21),
        convertToCoordinates(3, 26),

        convertToCoordinates(4, 1),
        convertToCoordinates(4, 6),
        convertToCoordinates(4, 12),
        convertToCoordinates(4, 15),
        convertToCoordinates(4, 21),
        convertToCoordinates(4, 26),

        convertToCoordinates(5, 1),
        convertToCoordinates(5, 2),
        convertToCoordinates(5, 3),
        convertToCoordinates(5, 4),
        convertToCoordinates(5, 5),
        convertToCoordinates(5, 6),
        convertToCoordinates(5, 7),
        convertToCoordinates(5, 8),
        convertToCoordinates(5, 9),
        convertToCoordinates(5, 10),
        convertToCoordinates(5, 11),
        convertToCoordinates(5, 12),
        convertToCoordinates(5, 13),
        convertToCoordinates(5, 14),
        convertToCoordinates(5, 15),
        convertToCoordinates(5, 16),
        convertToCoordinates(5, 17),
        convertToCoordinates(5, 18),
        convertToCoordinates(5, 19),
        convertToCoordinates(5, 20),
        convertToCoordinates(5, 21),
        convertToCoordinates(5, 22),
        convertToCoordinates(5, 23),
        convertToCoordinates(5, 24),
        convertToCoordinates(5, 25),
        convertToCoordinates(5, 26),

        convertToCoordinates(6, 1),
        convertToCoordinates(6, 6),
        convertToCoordinates(6, 9),
        convertToCoordinates(6, 18),
        convertToCoordinates(6, 21),
        convertToCoordinates(6, 26),

        convertToCoordinates(7, 1),
        convertToCoordinates(7, 6),
        convertToCoordinates(7, 9),
        convertToCoordinates(7, 18),
        convertToCoordinates(7, 21),
        convertToCoordinates(7, 26),

        convertToCoordinates(8, 1),
        convertToCoordinates(8, 2),
        convertToCoordinates(8, 3),
        convertToCoordinates(8, 4),
        convertToCoordinates(8, 5),
        convertToCoordinates(8, 6),
        convertToCoordinates(8, 9),
        convertToCoordinates(8, 10),
        convertToCoordinates(8, 11),
        convertToCoordinates(8, 12),
        convertToCoordinates(8, 15),
        convertToCoordinates(8, 16),
        convertToCoordinates(8, 17),
        convertToCoordinates(8, 18),
        convertToCoordinates(8, 21),
        convertToCoordinates(8, 22),
        convertToCoordinates(8, 23),
        convertToCoordinates(8, 24),
        convertToCoordinates(8, 25),
        convertToCoordinates(8, 26),

        convertToCoordinates(9, 6),
        convertToCoordinates(9, 21),

        convertToCoordinates(10, 6),
        convertToCoordinates(10, 21),

        convertToCoordinates(11, 6),
        convertToCoordinates(11, 21),

        convertToCoordinates(12, 6),
        convertToCoordinates(12, 21),

        convertToCoordinates(13, 6),
        convertToCoordinates(13, 21),

        convertToCoordinates(14, 6),
        convertToCoordinates(14, 21),

        convertToCoordinates(15, 6),
        convertToCoordinates(15, 21),

        convertToCoordinates(16, 6),
        convertToCoordinates(16, 21),

        convertToCoordinates(17, 6),
        convertToCoordinates(17, 21),

        convertToCoordinates(18, 6),
        convertToCoordinates(18, 21),

        convertToCoordinates(19, 6),
        convertToCoordinates(19, 21),

        convertToCoordinates(20, 1),
        convertToCoordinates(20, 2),
        convertToCoordinates(20, 3),
        convertToCoordinates(20, 4),
        convertToCoordinates(20, 5),
        convertToCoordinates(20, 6),
        convertToCoordinates(20, 7),
        convertToCoordinates(20, 8),
        convertToCoordinates(20, 9),
        convertToCoordinates(20, 10),
        convertToCoordinates(20, 11),
        convertToCoordinates(20, 12),
        convertToCoordinates(20, 15),
        convertToCoordinates(20, 16),
        convertToCoordinates(20, 17),
        convertToCoordinates(20, 18),
        convertToCoordinates(20, 19),
        convertToCoordinates(20, 20),
        convertToCoordinates(20, 21),
        convertToCoordinates(20, 22),
        convertToCoordinates(20, 23),
        convertToCoordinates(20, 24),
        convertToCoordinates(20, 25),
        convertToCoordinates(20, 26),

        convertToCoordinates(21, 1),
        convertToCoordinates(21, 6),
        convertToCoordinates(21, 12),
        convertToCoordinates(21, 15),
        convertToCoordinates(21, 21),
        convertToCoordinates(21, 26),

        convertToCoordinates(22, 1),
        convertToCoordinates(22, 6),
        convertToCoordinates(22, 12),
        convertToCoordinates(22, 15),
        convertToCoordinates(22, 21),
        convertToCoordinates(22, 26),

        convertToCoordinates(23, 1),
        convertToCoordinates(23, 2),
        convertToCoordinates(23, 3),
        convertToCoordinates(23, 6),
        convertToCoordinates(23, 7),
        convertToCoordinates(23, 8),
        convertToCoordinates(23, 9),
        convertToCoordinates(23, 10),
        convertToCoordinates(23, 11),
        convertToCoordinates(23, 12),
        convertToCoordinates(23, 15),
        convertToCoordinates(23, 16),
        convertToCoordinates(23, 17),
        convertToCoordinates(23, 18),
        convertToCoordinates(23, 19),
        convertToCoordinates(23, 20),
        convertToCoordinates(23, 21),
        convertToCoordinates(23, 24),
        convertToCoordinates(23, 25),
        convertToCoordinates(23, 26),

        convertToCoordinates(24, 3),
        convertToCoordinates(24, 6),
        convertToCoordinates(24, 9),
        convertToCoordinates(24, 18),
        convertToCoordinates(24, 21),
        convertToCoordinates(24, 24),

        convertToCoordinates(25, 3),
        convertToCoordinates(25, 6),
        convertToCoordinates(25, 9),
        convertToCoordinates(25, 18),
        convertToCoordinates(25, 21),
        convertToCoordinates(25, 24),

        convertToCoordinates(26, 1),
        convertToCoordinates(26, 2),
        convertToCoordinates(26, 3),
        convertToCoordinates(26, 4),
        convertToCoordinates(26, 5),
        convertToCoordinates(26, 6),
        convertToCoordinates(26, 9),
        convertToCoordinates(26, 10),
        convertToCoordinates(26, 11),
        convertToCoordinates(26, 12),
        convertToCoordinates(26, 15),
        convertToCoordinates(26, 16),
        convertToCoordinates(26, 17),
        convertToCoordinates(26, 18),
        convertToCoordinates(26, 21),
        convertToCoordinates(26, 22),
        convertToCoordinates(26, 23),
        convertToCoordinates(26, 24),
        convertToCoordinates(26, 25),
        convertToCoordinates(26, 26),

        convertToCoordinates(27, 1),
        convertToCoordinates(27, 12),
        convertToCoordinates(27, 15),
        convertToCoordinates(27, 26),

        convertToCoordinates(28, 1),
        convertToCoordinates(28, 12),
        convertToCoordinates(28, 15),
        convertToCoordinates(28, 26),

        convertToCoordinates(29, 1),
        convertToCoordinates(29, 2),
        convertToCoordinates(29, 3),
        convertToCoordinates(29, 4),
        convertToCoordinates(29, 5),
        convertToCoordinates(29, 6),
        convertToCoordinates(29, 7),
        convertToCoordinates(29, 8),
        convertToCoordinates(29, 9),
        convertToCoordinates(29, 10),
        convertToCoordinates(29, 11),
        convertToCoordinates(29, 12),
        convertToCoordinates(29, 13),
        convertToCoordinates(29, 14),
        convertToCoordinates(29, 15),
        convertToCoordinates(29, 16),
        convertToCoordinates(29, 17),
        convertToCoordinates(29, 18),
        convertToCoordinates(29, 19),
        convertToCoordinates(29, 20),
        convertToCoordinates(29, 21),
        convertToCoordinates(29, 22),
        convertToCoordinates(29, 23),
        convertToCoordinates(29, 24),
        convertToCoordinates(29, 25),
        convertToCoordinates(29, 26)
    ]
};

function convertToCoordinates(row: number, column: number): CollectibleCoordinate {
    return {
        centerX: column * 15,
        centerY: row * 15
    };
}
